import Head from 'next/head'
import BasicTable from './components/BasicTable'
import FilteringTable from './components/FilteringTable'
// import LandingPage from './components/LandingPage'
// import DataTable from './DataTable'
import SortingTable from './components/SortingTable'
import MOCK_DATA from './components/MOCK_DATA.json'
import {COLUMNS} from './components/columns'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <DataTable></DataTable> */}

      {/* <LandingPage></LandingPage> */}
      {/* <BasicTable></BasicTable> */}
      {/* <SortingTable></SortingTable> */}
      {/* <FilteringTable /> */}
      <FilteringTable searchable pagination data1={MOCK_DATA} columns1={COLUMNS}/>
    </>
  )
}
